/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITimiDAN } from "./ITimiDAN";
export type { IclaimNFT } from "./IclaimNFT";
export type { NFTDrop } from "./NFTDrop";
export type { TimiDAN } from "./TimiDAN";
