/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITimiDAN__factory } from "./ITimiDAN__factory";
export { IclaimNFT__factory } from "./IclaimNFT__factory";
